#!/bin/bash

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"


# clear existing grub config
rm -f \
/boot/grub2/grub.cfg \
/boot/efi/EFI/fedora/grub.cfg

# reinstall the grub modules
dnf reinstall -y \
grub2-common \
grub2-efi-* \
shim-*

# reconfigure the grub.cfg for btrfs etc...
sed -i '1i set btrfs_relative_path="yes"' /boot/efi/EFI/fedora/grub.cfg
sed -i 's/--root-dev-only//g' /boot/efi/EFI/fedora/grub.cfg

# regenerate grub menu
grub2-mkconfig -o /boot/grub2/grub.cfg
