#!/bin/bash


# configuration arrays
copr_repos=(
"chriscowleyunix/better_fonts"
"kwizart/fedy"
"phracek/PyCharm")

dnf_configure=(
"deltarpm=true"
"fastestmirror=true"
"max_parallel_downloads=10"
"exclude=libreoffice-*,rhythmbox,unoconv"
)

subvolumes=(
"home"
"opt"
"var/cache"
"var/crash"
"var/lib/libvirt/images"
"var/lib/mock"
"var/log"
"var/spool"
"var/tmp"
"var/www"
)

kernel_parameters=(
"acpi.prefer_microsoft_guid=1"
"fbcon=nodefer"
"iommu=pt"
"nmi_watchdog=0"
"pcie_aspm=off"
"pci=noaer"
"preempt=full"
"vt.global_cursor_default=0"
)

nvidia_kernel=(
"modprobe.blacklist=nouveau"
"nvidia-drm.modeset=1"
"NVreg_PreserveVideoMemoryAllocations=1"
"NVreg_TemporaryFilePath=/var/tmp"
"rd.driver.blacklist=nouveau"
)

# package arrays

host_packages=( \
dialog \
gdisk \
hwinfo \
)

base_packages=( \
@minimal-environment \
bash-completion \
btrfs-progs \
cracklib \
cracklib-dicts \
cryptsetup \
finger \
git \
glibc-all-langpacks \
glibc-langpack-en \
grub2-common \
grub2-efi-x64 \
grub2-efi-x64-modules \
grub2-tools \
grubby \
inotify-tools \
kernel \
langpacks-en \
make \
polkit \
shim \
tpm2-tools \
tpm2-tss \
vim \
)

app_packages=( \
acl \
acpid \
automake \
btop \
btrfs-assistant \
bzip2 \
cabextract \
celluloid \
compat-ffmpeg4 \
compsize \
cpio \
cryfs \
curl \
darktable \
dconf \
dconf-editor \
dex-autostart \
dialog \
diffoscope \
distrobox \
dkms \
dmidecode \
duf \
efibootmgr \
efi-filesystem \
elfutils-libelf-devel \
fedy \
fira-code-fonts \
firewall-config \
flac \
flatpak-builder \
foliate \
fontconfig \
fwupd \
gcc \
gcc-c++ \
gedit \
gimp \
gimp-help-en_GB \
gimp-layer-via-copy-cut \
gimp-resynthesizer \
gnome-extensions-app \
gnome-shell-extension-gpaste \
gnome-shell-extension-pop-shell \
gnome-tweaks \
google-roboto-* \
gparted \
grub2-efi-ia32 \
grub2-pc \
grub2-pc-modules \
grub2-tools-efi \
grub2-tools-extra \
grub2-tools-minimal \
gtksourceview3 \
hadolint \
handbrake \
handbrake-gui \
hddtemp \
htop \
hugo \
hwinfo \
hyperfine \
iotop \
jpegoptim \
kernel-devel \
kernel-headers \
kodi \
kodi-pvr-hts \
libglvnd-devel \
libglvnd-glx \
libglvnd-opengl \
libva-utils \
lm_sensors \
lshw \
lzip \
lzop \
mediainfo \
meld \
mkvtoolnix \
mkvtoolnix-gui \
mock \
mokutil \
mozilla-fira* \
mpv \
mscore-fonts-all \
nano \
neofetch \
nextcloud-client \
nvtop \
openssl \
optipng \
p7zip \
p7zip-plugins \
paperwork \
pastebinit \
pciutils \
peek \
pkgconfig \
power-profiles-daemon \
rawtherapee \
roboto-fontface-* \
rpi-imager \
rsync \
shellcheck \
shim-ia32 \
shim-x64 \
shotwell \
skanlite \
sqlitebrowser \
sushi \
tar \
tesseract \
tigervnc \
unrar \
unzip \
uxplay \
vlc \
xorg-x11-font-utils \
xsane \
xset \
yamllint \
yt-dlp \
)

gaming_packages=( \
gnome-sudoku \
goverlay \
lutris \
mangohud \
steam \
steam-devices \
supertuxkart \
unace \
)

virtualization_packages=( \
edk2-ovmf \
guestfs-tools \
libosinfo \
libvirt \
qemu-img \
qemu-kvm \
swtpm \
virt-install \
virt-manager \
virt-viewer \
)

flatpak_packages=( \
com.bitwarden.desktop \
com.discordapp.Discord \
com.github.iwalton3.jellyfin-media-player \
com.github.tchx84.Flatseal \
com.mattjakeman.ExtensionManager \
com.obsproject.Studio \
com.steamgriddb.steam-rom-manager \
"flathub org.remmina.Remmina"
im.riot.Riot \
io.github.flattool.Warehouse \
io.github.Foldex.AdwSteamGtk \
io.missioncenter.MissionCenter \
net.davidotek.pupgui2 \
org.filezillaproject.Filezilla \
org.gnome.Connections \
org.gnome.Photos \
org.gnome.World.PikaBackup \
org.libreoffice.LibreOffice \
org.mozilla.Thunderbird \
org.nickvision.tubeconverter \
org.phoenicis.playonlinux \
org.raspberrypi.rpi-imager \
org.signal.Signal \
)
